version: '3.8'

services:
    # Standard headless MCP server
    browser-use-headless:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: browser-use-mcp-headless
        environment:
            - BROWSER_USE_HEADLESS=true
            - GOOGLE_API_KEY=${GOOGLE_API_KEY}
        stdin_open: true
        tty: true

    # VNC-enabled MCP server for debugging
    browser-use-vnc:
        build:
            context: .
            dockerfile: Dockerfile.vnc
        container_name: browser-use-mcp-vnc
        environment:
            - BROWSER_USE_HEADLESS=false
            - GOOGLE_API_KEY=${GOOGLE_API_KEY}
        ports:
            - '5900:5900' # VNC port
        stdin_open: true
        tty: true
        shm_size: 2g # Increase shared memory for browser
